### ISSUE TITLE
URI scheme 'http' is not supported

### ISSUE THREAD

**Issue by theray33** [stellasia/pygds#1]
URI scheme 'http' is not supported. Supported URI schemes are ['bolt', 'bolt+ssc', 'bolt+s', 'neo4j', 'neo4j+ssc', 'neo4j+s']. Examples: bolt://host[:port] or neo4j://host[:port][?routing_context]

Will the 'http' be supported in future releases of this library?

**Comment by stellasia** [comment]
Hi @theray33 , pygds fully rely on the [python neo4j driver](https://github.com/neo4j/neo4j-python-driver) to connect to neo4j, so if the driver doesn't support http, pygds won't. However, why is it impossible for you to use, for instance, bolt?

**Comment by theray33** [comment]
Hi @stellasia, I just started using Neo4j so please forgive me if my further questions are a bit stupid. 
I have a http address where my Neo4j database is hosted. Till now I just used py2neo to run simple queries but now I am not able to run GDS queries using py2neo, so I decided to use pygds. So is there a way to convert the html address to bolt or if there is any better solution please do let me know.
